apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: zceh264nh-dotnet-basic
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: rhtap-quay-quay-rhtap-quay.apps.rosa.kx-c17f7960d0.chec.p3.openshiftapps.com/rhtap/rhtap-qe-dotnet-basic:93c6530476737d5526d8610d1514703e9e59d3a4@sha256:f8830be1527a0c13966db49837adf2bdc47b24a5dc4a75e34ce61d07a7bc9c2e
          name: container-image
